export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
}

export const emojiItems: EmojiItem[] = [
  // Smileys & Emotion
  {emoji: "😀", name: "grinning face", category: "smileys-emotion"},
  {emoji: "😃", name: "grinning face with big eyes", category: "smileys-emotion"},
  {emoji: "😄", name: "grinning face with smiling eyes", category: "smileys-emotion"},
  {emoji: "😁", name: "beaming face with smiling eyes", category: "smileys-emotion"},
  {emoji: "😆", name: "grinning squinting face", category: "smileys-emotion"},
  {emoji: "😅", name: "grinning face with sweat", category: "smileys-emotion"},
  {emoji: "🤣", name: "rolling on the floor laughing", category: "smileys-emotion"},
  {emoji: "😂", name: "face with tears of joy", category: "smileys-emotion"},
  {emoji: "🙂", name: "slightly smiling face", category: "smileys-emotion"},
  {emoji: "😊", name: "smiling face with smiling eyes", category: "smileys-emotion"},
  {emoji: "😇", name: "smiling face with halo", category: "smileys-emotion"},
  {emoji: "🥰", name: "smiling face with hearts", category: "smileys-emotion"},
  {emoji: "😍", name: "smiling face with heart-eyes", category: "smileys-emotion"},
  {emoji: "🤩", name: "star-struck", category: "smileys-emotion"},
  {emoji: "😘", name: "face blowing a kiss", category: "smileys-emotion"},
  {emoji: "😋", name: "face savoring food", category: "smileys-emotion"},
  {emoji: "😜", name: "winking face with tongue", category: "smileys-emotion"},
  {emoji: "🤪", name: "zany face", category: "smileys-emotion"},
  {emoji: "🤔", name: "thinking face", category: "smileys-emotion"},
  {emoji: "🤗", name: "smiling face with open hands", category: "smileys-emotion"},
  {emoji: "😎", name: "smiling face with sunglasses", category: "smileys-emotion"},
  {emoji: "🤓", name: "nerd face", category: "smileys-emotion"},
  {emoji: "😢", name: "crying face", category: "smileys-emotion"},
  {emoji: "😭", name: "loudly crying face", category: "smileys-emotion"},
  {emoji: "😡", name: "pouting face", category: "smileys-emotion"},
  {emoji: "😱", name: "face screaming in fear", category: "smileys-emotion"},
  {emoji: "🥳", name: "partying face", category: "smileys-emotion"},
  {emoji: "🤯", name: "exploding head", category: "smileys-emotion"},
  {emoji: "😴", name: "sleeping face", category: "smileys-emotion"},
  {emoji: "🤤", name: "drooling face", category: "smileys-emotion"},
  // People & Body
  {emoji: "👋", name: "waving hand", category: "people-body"},
  {emoji: "👍", name: "thumbs up", category: "people-body"},
  {emoji: "👎", name: "thumbs down", category: "people-body"},
  {emoji: "👏", name: "clapping hands", category: "people-body"},
  {emoji: "🙌", name: "raising hands", category: "people-body"},
  {emoji: "🤝", name: "handshake", category: "people-body"},
  {emoji: "🙏", name: "folded hands", category: "people-body"},
  {emoji: "✌️", name: "victory hand", category: "people-body"},
  {emoji: "💪", name: "flexed biceps", category: "people-body"},
  {emoji: "🫶", name: "heart hands", category: "people-body"},
  // Animals & Nature
  {emoji: "🐶", name: "dog face", category: "animals-nature"},
  {emoji: "🐱", name: "cat face", category: "animals-nature"},
  {emoji: "🐭", name: "mouse face", category: "animals-nature"},
  {emoji: "🐻", name: "bear face", category: "animals-nature"},
  {emoji: "🐼", name: "panda face", category: "animals-nature"},
  {emoji: "🦊", name: "fox face", category: "animals-nature"},
  {emoji: "🦁", name: "lion face", category: "animals-nature"},
  {emoji: "🐸", name: "frog face", category: "animals-nature"},
  {emoji: "🦄", name: "unicorn face", category: "animals-nature"},
  {emoji: "🐉", name: "dragon", category: "animals-nature"},
  {emoji: "🌸", name: "cherry blossom", category: "animals-nature"},
  {emoji: "🌻", name: "sunflower", category: "animals-nature"},
  {emoji: "🌈", name: "rainbow", category: "animals-nature"},
  {emoji: "⭐", name: "star", category: "animals-nature"},
  {emoji: "🌙", name: "crescent moon", category: "animals-nature"},
  // Food & Drink
  {emoji: "🍕", name: "pizza", category: "food-drink"},
  {emoji: "🍔", name: "hamburger", category: "food-drink"},
  {emoji: "🍟", name: "french fries", category: "food-drink"},
  {emoji: "🌮", name: "taco", category: "food-drink"},
  {emoji: "🍣", name: "sushi", category: "food-drink"},
  {emoji: "🍜", name: "steaming bowl", category: "food-drink"},
  {emoji: "🍰", name: "shortcake", category: "food-drink"},
  {emoji: "🍩", name: "doughnut", category: "food-drink"},
  {emoji: "🍪", name: "cookie", category: "food-drink"},
  {emoji: "🍦", name: "soft ice cream", category: "food-drink"},
  {emoji: "☕", name: "hot beverage", category: "food-drink"},
  {emoji: "🍺", name: "beer mug", category: "food-drink"},
  {emoji: "🍎", name: "red apple", category: "food-drink"},
  {emoji: "🍓", name: "strawberry", category: "food-drink"},
  {emoji: "🍌", name: "banana", category: "food-drink"},
  // Activities
  {emoji: "⚽", name: "soccer ball", category: "activities"},
  {emoji: "🏀", name: "basketball", category: "activities"},
  {emoji: "🎾", name: "tennis", category: "activities"},
  {emoji: "🏊", name: "person swimming", category: "activities"},
  {emoji: "🎮", name: "video game", category: "activities"},
  {emoji: "🎲", name: "game die", category: "activities"},
  {emoji: "🎨", name: "artist palette", category: "activities"},
  {emoji: "🎵", name: "musical note", category: "activities"},
  {emoji: "🎉", name: "party popper", category: "activities"},
  {emoji: "🏆", name: "trophy", category: "activities"},
  // Objects
  {emoji: "💡", name: "light bulb", category: "objects"},
  {emoji: "🔑", name: "key", category: "objects"},
  {emoji: "📱", name: "mobile phone", category: "objects"},
  {emoji: "💻", name: "laptop", category: "objects"},
  {emoji: "📷", name: "camera", category: "objects"},
  {emoji: "📚", name: "books", category: "objects"},
  {emoji: "🎁", name: "wrapped gift", category: "objects"},
  {emoji: "🔔", name: "bell", category: "objects"},
  {emoji: "🔒", name: "locked", category: "objects"},
  {emoji: "🏠", name: "house", category: "objects"},
  {emoji: "✉️", name: "envelope", category: "objects"},
  {emoji: "📌", name: "pushpin", category: "objects"},
  {emoji: "🔧", name: "wrench", category: "objects"},
  {emoji: "🎧", name: "headphone", category: "objects"},
  // Travel & Places
  {emoji: "🚗", name: "automobile", category: "travel-places"},
  {emoji: "✈️", name: "airplane", category: "travel-places"},
  {emoji: "🚢", name: "ship", category: "travel-places"},
  {emoji: "🏖️", name: "beach with umbrella", category: "travel-places"},
  {emoji: "🏔️", name: "snow-capped mountain", category: "travel-places"},
  {emoji: "🗼", name: "tokyo tower", category: "travel-places"},
  {emoji: "🗽", name: "statue of liberty", category: "travel-places"},
  {emoji: "🌍", name: "globe showing europe-africa", category: "travel-places"},
  {emoji: "🌏", name: "globe showing asia-australia", category: "travel-places"},
  {emoji: "🚀", name: "rocket", category: "travel-places"},
  // Symbols
  {emoji: "❤️", name: "red heart", category: "symbols"},
  {emoji: "💙", name: "blue heart", category: "symbols"},
  {emoji: "💚", name: "green heart", category: "symbols"},
  {emoji: "💛", name: "yellow heart", category: "symbols"},
  {emoji: "🖤", name: "black heart", category: "symbols"},
  {emoji: "💯", name: "hundred points", category: "symbols"},
  {emoji: "✅", name: "check mark button", category: "symbols"},
  {emoji: "❌", name: "cross mark", category: "symbols"},
  {emoji: "⚡", name: "high voltage", category: "symbols"},
  {emoji: "🔥", name: "fire", category: "symbols"},
  {emoji: "💤", name: "zzz", category: "symbols"},
  {emoji: "♻️", name: "recycling symbol", category: "symbols"},
  // Flags
  {emoji: "🏁", name: "chequered flag", category: "flags"},
  {emoji: "🚩", name: "triangular flag", category: "flags"},
  {emoji: "🏳️", name: "white flag", category: "flags"},
  {emoji: "🏴", name: "black flag", category: "flags"},
  {emoji: "🏳️‍🌈", name: "rainbow flag", category: "flags"},
];
